### ISSUE TITLE
crashfree(...) fails with 404

### ISSUE THREAD

**Issue by LeffelMania** [strongself/fabricio#21]
I suspect the URL scheme has changed with Fabric's recent dashboard update.
```
irb(main):022:0> client.app.crashfree('<app_id>', Time.new, Time.new - 10000, 'all')
JSON::ParserError: 757: unexpected token at '<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /total-sessions-scalar. Reason:
<pre>    Not Found</pre></p><br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                

</body>
</html>
'
	from /Users/alexleffelman/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/json-1.8.2/lib/json/common.rb:155:in `parse'
	from /Users/alexleffelman/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/json-1.8.2/lib/json/common.rb:155:in `parse'
	from /Users/alexleffelman/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fabricio-1.0.0/lib/fabricio/services/app_service.rb:93:in `total_sessions'
	from /Users/alexleffelman/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fabricio-1.0.0/lib/fabricio/services/app_service.rb:119:in `crashfree'
	from (irb):22
	from /Users/alexleffelman/.rbenv/versions/2.2.2/bin/irb:11:in `<main>'
irb(main):023:0> app_factory = AppRequestModelFactory::new
NameError: uninitialized constant AppRequestModelFactory
	from (irb):23
	from /Users/alexleffelman/.rbenv/versions/2.2.2/bin/irb:11:in `<main>'
irb(main):024:0> app_factory = AppRequestModelFactory.new
NameError: uninitialized constant AppRequestModelFactory
	from (irb):24
	from /Users/alexleffelman/.rbenv/versions/2.2.2/bin/irb:11:in `<main>'
```

**Comment by dwader** [comment]
Thanks for the feedback. I'll research it on the weekend.

**Comment by etolstoy** [comment]
Thanks for the feedback. I'll research it on the weekend.

**Comment by LeffelMania** [comment]
I'm sorry, I lied. My error was using `Time.new` directly and not having the correct order.

```
client.app.crashfree('<app_id>', (Time.new - 10000).to_i, Time.new.to_i, 'all')
```
worked as expected.

I don't Ruby much. 😁  Thanks!
