### ISSUE TITLE
Invalid Address Error at Client Initialisation

### ISSUE THREAD

**Issue by ongks** [strongself/fabricio#29]
Hi,
I am having issues with authentication at the client initialisation stage, and have followed the readme instructions. Do you happen to know a fix for the following error thrown?

```
/Users/macadmin/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/ipaddr.rb:563:in `in6_addr': invalid address (IPAddr::InvalidAddressError)
        from /Users/macadmin/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/ipaddr.rb:500:in `initialize'
        from /Users/macadmin/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/ipaddr.rb:518:in `new'
        from /Users/macadmin/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/ipaddr.rb:518:in `coerce_other'
        from /Users/macadmin/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/ipaddr.rb:174:in `include?'
        from /Users/macadmin/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/uri/generic.rb:1541:in `block in find_proxy'
        from /Users/macadmin/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/uri/generic.rb:1530:in `scan'
        from /Users/macadmin/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/uri/generic.rb:1530:in `find_proxy'
        from /Users/macadmin/.rvm/gems/ruby-2.4.1/gems/faraday-0.12.1/lib/faraday/connection.rb:88:in `block in initialize'
        from /Users/macadmin/.rvm/gems/ruby-2.4.1/gems/faraday-0.12.1/lib/faraday/options.rb:75:in `fetch'
        from /Users/macadmin/.rvm/gems/ruby-2.4.1/gems/faraday-0.12.1/lib/faraday/connection.rb:83:in `initialize'
        from /Users/macadmin/.rvm/gems/ruby-2.4.1/gems/faraday-0.12.1/lib/faraday.rb:67:in `new'
        from /Users/macadmin/.rvm/gems/ruby-2.4.1/gems/faraday-0.12.1/lib/faraday.rb:67:in `new'
        from /Users/macadmin/.rvm/gems/ruby-2.4.1/gems/fabricio-1.2.0/lib/fabricio/authorization/authorization_client.rb:85:in `obtain_auth_data'
        from /Users/macadmin/.rvm/gems/ruby-2.4.1/gems/fabricio-1.2.0/lib/fabricio/authorization/authorization_client.rb:45:in `perform_authorization'
        from /Users/macadmin/.rvm/gems/ruby-2.4.1/gems/fabricio-1.2.0/lib/fabricio/authorization/authorization_client.rb:22:in `auth'
        from /Users/macadmin/.rvm/gems/ruby-2.4.1/gems/fabricio-1.2.0/lib/fabricio/client/client.rb:82:in `obtain_session'
        from /Users/macadmin/.rvm/gems/ruby-2.4.1/gems/fabricio-1.2.0/lib/fabricio/client/client.rb:55:in `initialize'
        from app/services/fabric.rb:8:in `new'
        from app/services/fabric.rb:8:in `get_app_metrics'
        from app/services/fabric.rb:32:in `<main>'

```

Thank you for your time.

**Comment by etolstoy** [comment]
Hi, @ongks! Can you show your code?

**Comment by etolstoy** [comment]
Closing because of insufficient data.
